### ISSUE TITLE
install slackellive64-openbox-7.0.iso, lilo apparently fails

### ISSUE THREAD

**Issue by fbrau** [djemos/slackel-live#1]
Hi there... I don't know if this goes here but I lost my user/password in the slackel forum and I will forget this "bug" awaiting for my new account...

I'm installing with the gui installer. I want lilo/elilo as bootloeader...
all good (I guess) but then a popup saying ERROR (don't remember the words but the message was that generic)

chrooting in the install partition to check what failed I try "lilo" and it fails:
"Fatal: Image name, label or alias too long: 'Slackel-openbox-7.0' " (pretty trivial, right?)
  
Also, assuming the error in the installer was this, what else did the install missed or this was the last stage?

**Comment by djemos** [comment]
This has been solved with recompiled lilo.
The  label = slackel-openbox-7.0 changed to label = Slackel. Because it was too long string for lilo. You can upgrade lilo or just edit liloconfig as root and change label two apperances to label = Slackel. Then run lilo
